# Site settings
name: JD Assessoria Florestal e Ambiental
address: Rua Buenos Aires, 1013, Bairro Jardim Seminário - Francisco Beltrão - PR
title: JD Assessoria Florestal e Ambiental
email_ediane: edianedaleffe@gmail.com
email_jurandi: jurandi@creapr.org.br
telefone_fixo: (46) 3524-9023
celular_ediane: (46) 8805-1492
celular_jurandi: (46) 9975-0243
hangout_ediane: edianedaleffe@gmail.com
facebook_link: https://www.facebook.com/JDAssessoriaFlorestalLTDA
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jd.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

github: git@github.com:jdassessoria/jdassessoria.github.io.git
